### ISSUE TITLE
Question, I don't know where to contact you other than this

### ISSUE THREAD

**Issue by geocine** [tobipch/Times2Stats#26]
Are you going to put this up on github? http://tobip.ch/letter_pair_generator/

**Comment by tobipch** [comment]
Hello ;)

Not planned to do so, since I'm not developing it further anymore.

But I can do it if you want...

Should I?

**Comment by geocine** [comment]
Yeah if its ok because I wanted to fork it to serve as a backup as well in case you decide to remove it from  your hosting
